name: microblog-trigger

on:
  push:

jobs:
  trigger-update:
    runs-on: ubuntu-latest
    steps:
      - run: gh workflow run render.yml --ref smallweb --repo sio/potyarkin.ml
        env:
          GITHUB_TOKEN: ${{ secrets.PAGES_TOKEN }}
